---

- name: Get OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution }}.yml"
   - "{{ ansible_os_family }}.yml"
  tags: always

- name: Install the SNMP package
  apt: name={{ snmpd['pkg']['name'] }} state=latest
  tags: pkg

- name: Configure SNMP
  template:
    src: snmpd.conf.j2
    dest: "{{ snmpd['cfg']['path'] }}"
  notify: restart SNMP
  tags: cfg

- name: Enable the SNMP service
  service:
    name: "{{ snmpd['svc']['name'] }}"
    state: started
    enabled: yes
  tags: svc
